import type { Metadata } from 'next';
import Link from 'next/link';
import { SITE } from '@/lib/config';

export const metadata: Metadata = {
  title: { absolute: 'Terms of Service | Trust Proof Roofing' },
  description: 'Terms of Service for Trust Proof Roofing LLC. Governing the use of our website and instant quote tool.',
  alternates: { canonical: `${SITE.url}/terms` },
  robots: { index: false, follow: false },
};

export default function TermsPage() {
  return (
    <>
      {/* Hero */}
      <section className="bg-brand-800 text-white py-16">
        <div className="max-w-7xl mx-auto px-4">
          <nav className="text-brand-300 text-sm mb-4">
            <Link href="/" className="hover:text-white">Home</Link>
            <span className="mx-2">›</span>
            <span>Terms of Service</span>
          </nav>
          <h1 className="font-heading text-4xl font-bold mb-3">Terms of Service</h1>
          <p className="text-brand-200 text-lg">Last updated: March 18, 2026</p>
        </div>
      </section>

      {/* Content */}
      <section className="py-16 bg-white">
        <div className="max-w-3xl mx-auto px-4">
          <div className="prose prose-gray max-w-none">

            <p className="text-gray-600 text-base leading-relaxed mb-8">
              These Terms of Service govern your use of the Trust Proof Roofing website located at{' '}
              <a href="https://trustproofroofing.com" className="text-brand-700 hover:underline">trustproofroofing.com</a>.
              By accessing or using this website, you agree to these terms. If you do not agree, please do not use this site.
            </p>

            {/* Section 1 */}
            <div className="mb-10">
              <h2 className="text-xl font-bold text-gray-900 mb-3">1. Informational Purpose</h2>
              <p className="text-gray-600 leading-relaxed">
                This website is provided for general informational purposes only. The content on this site — including descriptions of services, project photos, warranty information, and pricing guidance — is intended to help Connecticut homeowners understand roofing services available in their area. Nothing on this website constitutes a warranty, guarantee, or binding commitment of any kind unless expressly stated in a separate signed agreement.
              </p>
            </div>

            {/* Section 2 */}
            <div className="mb-10">
              <h2 className="text-xl font-bold text-gray-900 mb-3">2. Instant Quote Tool — Estimates Only</h2>
              <p className="text-gray-600 leading-relaxed mb-3">
                The Instant Quote tool on this website uses publicly available satellite and building data to generate estimated price ranges for roofing projects. These estimates are provided as a convenience only and are subject to the following limitations:
              </p>
              <ul className="list-disc pl-6 space-y-2 text-gray-600">
                <li>Estimates are based on approximate roof measurements derived from third-party data sources and may not reflect actual conditions at your property.</li>
                <li>Estimates do not account for hidden damage, structural issues, accessibility constraints, or other site-specific factors discovered during inspection.</li>
                <li>Submitting your information through the Instant Quote tool does not create a contract, obligation, or commitment of any kind by either party.</li>
                <li>An estimate provided by the Instant Quote tool is not a binding bid, proposal, or offer.</li>
              </ul>
              <p className="text-gray-600 leading-relaxed mt-3">
                Actual project pricing is determined only after an on-site or drone assessment and will be provided in a formal written estimate.
              </p>
            </div>

            {/* Section 3 */}
            <div className="mb-10">
              <h2 className="text-xl font-bold text-gray-900 mb-3">3. Roofing Agreement Governs All Work</h2>
              <p className="text-gray-600 leading-relaxed">
                All roofing work performed by Trust Proof Roofing LLC is governed exclusively by a separate, signed Roofing Agreement entered into between Trust Proof Roofing LLC and the property owner prior to the commencement of any work. No information, estimate, or communication on this website — including any quote generated by the Instant Quote tool — creates any obligation for Trust Proof Roofing LLC to perform work or for any property owner to engage our services. Only a fully executed written Roofing Agreement, signed by an authorized representative of Trust Proof Roofing LLC, constitutes a binding agreement.
              </p>
            </div>

            {/* Section 4 */}
            <div className="mb-10">
              <h2 className="text-xl font-bold text-gray-900 mb-3">4. Intellectual Property</h2>
              <p className="text-gray-600 leading-relaxed">
                All content on this website — including but not limited to text, copy, logos, graphics, photographs, page layouts, and the Trust Proof Roofing name and brand — is the exclusive property of Trust Proof Roofing LLC and is protected by applicable United States copyright and trademark law. You may not reproduce, distribute, modify, republish, or use any content from this website for commercial purposes without prior written permission from Trust Proof Roofing LLC. Limited personal, non-commercial use (such as printing a page for reference) is permitted provided that all copyright and proprietary notices are preserved.
              </p>
            </div>

            {/* Section 5 */}
            <div className="mb-10">
              <h2 className="text-xl font-bold text-gray-900 mb-3">5. Limitation of Liability</h2>
              <p className="text-gray-600 leading-relaxed mb-3">
                To the maximum extent permitted by applicable law, Trust Proof Roofing LLC shall not be liable for any direct, indirect, incidental, consequential, or special damages arising from or in connection with your use of this website or reliance on any information provided herein, including but not limited to:
              </p>
              <ul className="list-disc pl-6 space-y-2 text-gray-600">
                <li>Errors, inaccuracies, or omissions in website content.</li>
                <li>Reliance on pricing estimates generated by the Instant Quote tool.</li>
                <li>Interruption or unavailability of the website.</li>
                <li>Any third-party content or links referenced on this site.</li>
              </ul>
              <p className="text-gray-600 leading-relaxed mt-3">
                Your use of this website is at your own risk. The website is provided on an "as is" and "as available" basis without warranties of any kind, either express or implied.
              </p>
            </div>

            {/* Section 6 */}
            <div className="mb-10">
              <h2 className="text-xl font-bold text-gray-900 mb-3">6. Governing Law</h2>
              <p className="text-gray-600 leading-relaxed">
                These Terms of Service are governed by and construed in accordance with the laws of the State of Connecticut, without regard to its conflict of law provisions. Any disputes arising under or in connection with these terms shall be subject to the exclusive jurisdiction of the state and federal courts located in Hartford County, Connecticut.
              </p>
            </div>

            {/* Section 7 */}
            <div className="mb-10">
              <h2 className="text-xl font-bold text-gray-900 mb-3">7. Changes to These Terms</h2>
              <p className="text-gray-600 leading-relaxed">
                Trust Proof Roofing LLC reserves the right to update or modify these Terms of Service at any time. Changes will be effective upon posting to this page with an updated date. Continued use of the website after changes are posted constitutes acceptance of the revised terms.
              </p>
            </div>

            {/* Section 8 */}
            <div className="mb-10">
              <h2 className="text-xl font-bold text-gray-900 mb-3">8. Contact</h2>
              <p className="text-gray-600 leading-relaxed mb-4">
                If you have questions about these Terms of Service, please contact us:
              </p>
              <div className="bg-gray-50 border border-gray-200 rounded-xl p-6">
                <p className="font-semibold text-gray-900 mb-1">Trust Proof Roofing LLC</p>
                <p className="text-gray-600 text-sm">Suffield, CT 06078</p>
                <p className="text-gray-600 text-sm">CT HIC #HIC.0703927</p>
                <p className="text-gray-600 text-sm mt-2">
                  Phone:{' '}
                  <a href="tel:9593338569" className="text-brand-700 hover:underline">{SITE.phone}</a>
                </p>
                <p className="text-gray-600 text-sm">
                  Email:{' '}
                  <a href={`mailto:${SITE.email}`} className="text-brand-700 hover:underline">{SITE.email}</a>
                </p>
              </div>
            </div>

          </div>
        </div>
      </section>
    </>
  );
}
